### ISSUE TITLE
GetState - no 'out' fadeDirection for PingPong transition between two states

### ISSUE THREAD

**Issue by Huppys** [wirmachenbunt/AutomataUI#1]
Dear @wirmachenbunt,

maybe it's just me but I'm surprised by the fact AutomataUI won't give only the 'in' value for PingPong transitions between two states.

For testing purposes I'd liked to realize a simple light to be toggle on and off. Why not using a PingPong transition? I thought I could use this for a fade in and fade out. Fade in is totally fine. But \*big irritation\* fade out is acting strange. FadeInOut pin is jumping from 1.0 to 0.0 fading to 1.0 and jump back to 0.0.

Why?

Attached you'll find the vvvv patch and the states.xml and transitions.xml contained in that patch.
[StateMachineTest.zip](https://github.com/wirmachenbunt/AutomataUI/files/1667615/StateMachineTest.zip)

Best,
Oliver

**Comment by wirmachenbunt** [comment]
hey oliver,
this is a known behaviour and of course not optimal. thing is, a pingpong transition could be started from any direction hence the statemachine does not know which direction is your preferred one 0-1 or 1-0. it could go either way. due to this problem the fadeinout does not make much sense with pingpong transition as they are defined right now. i‘m not saying there isn‘t a solution but it needs more thinking how to handle the case in the UI.

quick workaround, use stateactive and a linearfilter node.
